name: first_step

on:
    push:
      branches:
        - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2


            - name: Set up Docker Compose
              run: |
                docker compose up --build --abort-on-container-exit
           
            - name: Tear down Docker Compose
              if: always()
              run: docker compose down